import { createContext, useContext } from 'react';
import { business } from './content';
export const SeasonContext = createContext(null);
export const useSeason = () => useContext(SeasonContext);
export const seasonDesigns = {
  default: {
    key: 'default', ar: 'الأساسي', en: 'Signature', number: '01',
    image: '/assets/editorial/default.webp', position: '42% 50%',
    eyebrow: ['من الطبيعة، بكل عناية', 'NATURE, BEAUTIFULLY COMPOSED'],
    title: ['للمكان روح،', 'A living soul,'], accent: ['وللورد حكاية.', 'in every space.'],
    body: ['نصوغ من الزهور والنباتات حضورًا يليق بمكانك. من أول انطباع إلى عناية تدوم، تبدأ الحكاية مع بلقيس الورد.', 'Considered flowers, living greenery and thoughtful care. We bring nature into your space, from the first impression to the everyday.'],
    caption: ['فنّ الزهور وحُسن الضيافة', 'THE ART OF FLORAL HOSPITALITY'],
    note: ['طبيعة نختارها. تفاصيل نعتني بها.', 'Nature, curated. Details, considered.'],
    greeting: ['أهلًا بك في بلقيس الورد', 'Welcome to Balqees Floral'],
    message: ['لكل مكان جماله الخاص، ويسعدنا أن نكتشفه معك. ورد طبيعي، اختيارات مدروسة، وعناية تستمر.', 'Every space has its own beauty. Let us find it together through natural flowers, considered choices and lasting care.'],
    alt: ['تكوين زهور عاجية وأوراق زيتونية في فازة نحاسية', 'Ivory roses and olive foliage in an aged brass vessel'],
  },
  ramadan: {
    key: 'ramadan', ar: 'رمضان', en: 'Ramadan', number: '02',
    image: '/assets/editorial/ramadan.webp', position: '42% 55%',
    eyebrow: ['ليالٍ تضيئها السكينة', 'THE RAMADAN COLLECTION'],
    title: ['للّيل سكينة،', 'Evenings of peace,'], accent: ['وللضيافة نور.', 'a warmer welcome.'],
    body: ['ورد أبيض، ضوء فانوس، وتفاصيل تستقبل الشهر الكريم. تنسيقات رمضانية تمنح مساحات الضيافة دفئًا وطمأنينة.', 'Ivory blooms, lantern light and meaningful details. Thoughtful Ramadan styling that brings warmth and serenity to your hospitality spaces.'],
    caption: ['رمضان · ضوء وورد وسكينة', 'RAMADAN · LIGHT & SERENITY'],
    note: ['تفاصيل دافئة لليالي الشهر الكريم.', 'Thoughtful details for the holy month.'],
    greeting: ['رمضان مبارك', 'Ramadan Mubarak'],
    message: ['أهلّ الله عليكم الشهر بالخير والسكينة، وملأ بيوتكم وأيامكم نورًا وطمأنينة. كل عام وأنتم بخير من بلقيس الورد.', 'May the holy month bring peace, warmth and blessings to your home. With our warmest wishes, Balqees Floral.'],
    alt: ['فوانيس نحاسية مضاءة بجوار ورود بيضاء في فناء رمضاني', 'Candlelit brass lanterns and ivory flowers in an Arabian courtyard'],
  },
  eid: {
    key: 'eid', ar: 'عيد الفطر', en: 'Eid Al-Fitr', number: '03',
    image: '/assets/editorial/eid.webp', position: '42% 50%',
    eyebrow: ['للّقاء بهجته، وللعيد وردته', 'THE EID AL-FITR COLLECTION'],
    title: ['حين يُزهر العيد،', 'When joy blooms,'], accent: ['تكتمل البهجة.', 'Eid feels closer.'],
    body: ['زهور ناعمة وألوان مضيئة وتفاصيل تختصر فرحة اللقاء. نهيّئ معكم مساحة أجمل لاستقبال أحبابكم وضيوفكم.', 'Soft petals, luminous colours and details that celebrate being together. Make room for beautiful moments with those who matter.'],
    caption: ['عيد الفطر · بهجة تُهدى', 'EID AL-FITR · JOY IN BLOOM'],
    note: ['ورد يليق بفرحة اللقاء.', 'Flowers for the joy of coming together.'],
    greeting: ['عيدكم مبارك', 'Eid Mubarak'],
    message: ['تقبّل الله طاعاتكم، وأدام عليكم بهجة العيد وقرب الأحبة. كل عام وأيامكم مزهرة بالخير.', 'May your Eid be filled with joy, blessings and the company of loved ones. Wishing you beautiful days ahead.'],
    alt: ['ورود عاجية وفاوانيا وردية في ضوء صباحي مع هدية العيد', 'Ivory roses and blush peonies in morning light with an Eid gift'],
  },
  adha: {
    key: 'adha', ar: 'عيد الأضحى', en: 'Eid Al-Adha', number: '04',
    image: '/assets/editorial/adha-giving.webp', position: '40% 50%',
    eyebrow: ['أيام مباركة، وقلوب متآلفة', 'THE EID AL-ADHA COLLECTION'],
    title: ['للخير مواسم،', 'A season of giving,'], accent: ['وللعيد ألفة.', 'a feeling of home.'],
    body: ['ألوان الأرض، ودفء الضيافة، وورد يجمع القلوب. تفاصيل طبيعية مدروسة تحتفي بأيام العيد المباركة.', 'Earthy tones, generous hospitality and flowers that bring people together. Natural details for the blessed days of Eid.'],
    caption: ['عيد الأضحى · عطاء وألفة', 'EID AL-ADHA · WARMTH & GIVING'],
    note: ['ضيافة يملؤها الكرم والطمأنينة.', 'Hospitality filled with warmth and generosity.'],
    greeting: ['أضحى مبارك', 'Eid Al-Adha Mubarak'],
    message: ['أعاده الله عليكم بالخير والقبول، وجمعكم بمن تحبون على الفرح والعافية. كل عام وأنتم بخير.', 'May this blessed Eid bring acceptance, generosity and joyful moments with those you love. Warm wishes from Balqees Floral.'],
    alt: ['هدية عيد أنيقة وورود بيضاء وتمر في ضيافة دافئة', 'An elegant Eid gift with white roses and dates in warm morning light'],
  },
  hajj: {
    key: 'hajj', ar: 'موسم الحج', en: 'Hajj', number: '05',
    image: '/assets/editorial/hajj.webp', position: '50% 55%',
    eyebrow: ['من مكة، نُحسن استقبالهم', 'HOSPITALITY IN THE HOLY CITY'],
    title: ['لضيوف الرحمن،', 'For a sacred journey,'], accent: ['أجمل ترحيب.', 'a heartfelt welcome.'],
    body: ['في موسم الرحلة المباركة، نعتني بتفاصيل استقبال ضيوف الرحمن. زهور ونباتات وتجهيز موسمي للفنادق ومرافق الضيافة في مكة.', 'Welcoming the guests of the Holy City with care. Seasonal flowers, greenery and hospitality styling for hotels and reception spaces in Makkah.'],
    caption: ['مكة المكرمة · شرف الضيافة', 'MAKKAH · THE HONOUR OF HOSPITALITY'],
    note: ['عناية بالتفاصيل، وترحيب من القلب.', 'Considered details. A welcome from the heart.'],
    greeting: ['حج مبرور وسعي مشكور', 'A blessed Hajj'],
    message: ['أهلًا بضيوف الرحمن في مكة المكرمة. نسأل الله لكم حجًا مبرورًا، وسعيًا مشكورًا، وعودةً سالمةً إلى أحبابكم.', 'Welcome to the guests of the Holy City. May your pilgrimage be accepted and your journey home be safe.'],
    alt: ['صورة فعلية للكعبة المشرفة والمسجد الحرام في مكة المكرمة', 'A photograph of the Kaaba at Masjid al-Haram in Makkah'],
  },
  national: {
    key: 'national', ar: 'اليوم الوطني', en: 'National Day', number: '06',
    image: '/assets/editorial/national.webp', position: '40% 50%',
    eyebrow: ['جذور أصيلة، وحضور يزهر', 'THE SAUDI NATIONAL DAY COLLECTION'],
    title: ['في القلب وطن،', 'Rooted in heritage,'], accent: ['وفي الدار ورد.', 'growing with pride.'],
    body: ['من خضرة النخيل إلى بياض الورد ودفء القهوة. نحتفي بروح المملكة في تفاصيل ضيافة تجمع أصالة المكان وجمال الطبيعة.', 'From green palms and white roses to the warmth of Arabic coffee. Celebrate the spirit of Saudi Arabia through authentic, considered hospitality.'],
    caption: ['اليوم الوطني · أصالة وانتماء', 'SAUDI NATIONAL DAY · ROOTS & PRIDE'],
    note: ['أخضر يعبّر عن الفخر والانتماء.', 'Green with pride. Rooted in belonging.'],
    greeting: ['دام عزّك يا وطن', 'With pride, Saudi Arabia'],
    message: ['نحتفي بوطنٍ يزهر بالطموح، وبأرضٍ تجمع الأصالة والجمال. كل عام والمملكة في عزّ وأمان وازدهار.', 'Celebrating a nation of ambition, heritage and beauty. Wishing Saudi Arabia continued peace and prosperity.'],
    alt: ['دلة قهوة نحاسية وورود بيضاء ونخيل في مشهد ضيافة سعودي', 'A brass dallah, white roses and date palms in a Saudi hospitality setting'],
  },
};
export const whatsappHref = (message = '') => `https://wa.me/966${business.whatsapp.slice(1)}${message ? `?text=${encodeURIComponent(message)}` : ''}`;
