import { useEffect, useMemo, useState } from 'react';
import { Building2, FileClock, Fingerprint, RefreshCw, Search, ShieldAlert, ShieldCheck, UserCheck, UserMinus, UsersRound, X } from 'lucide-react';
import { supabase } from '../../lib/supabase';

const fmt=(d,lang)=>d?new Intl.DateTimeFormat(lang==='ar'?'ar-SA':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(d)):'—';
export default function AdminOrganizationTeam({lang}){
  const ar=lang==='ar'; const[members,setMembers]=useState([]),[orgs,setOrgs]=useState([]),[profiles,setProfiles]=useState({}),[audits,setAudits]=useState([]),[q,setQ]=useState(''),[org,setOrg]=useState(''),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  async function load(){setLoading(true);const[o,m,a]=await Promise.all([supabase.from('organizations').select('id,display_name,status').order('display_name'),supabase.from('organization_members').select('*').order('joined_at',{ascending:false}),supabase.from('organization_member_audit').select('*').order('created_at',{ascending:false}).limit(120)]);setOrgs(o.data||[]);setMembers(m.data||[]);setAudits(a.data||[]);const ids=[...new Set((m.data||[]).map(x=>x.user_id))];if(ids.length){const{data}=await supabase.from('customer_profiles').select('id,full_name,email').in('id',ids);setProfiles(Object.fromEntries((data||[]).map(x=>[x.id,x])));}setLoading(false);}
  useEffect(()=>{load();},[]);
  const orgMap=useMemo(()=>Object.fromEntries(orgs.map(x=>[x.id,x])),[orgs]);
  const shown=members.filter(x=>{if(org&&x.organization_id!==org)return false;const p=profiles[x.user_id]||{};return `${p.full_name||''} ${p.email||''} ${x.member_role||''} ${orgMap[x.organization_id]?.display_name||''}`.toLowerCase().includes(q.toLowerCase())});
  const selectedAudit=selected?audits.filter(a=>a.organization_id===selected.organization_id&&a.target_user_id===selected.user_id).slice(0,12):[];
  const selectedIsLastOwner=Boolean(selected?.member_role==='owner'&&members.filter(m=>m.organization_id===selected.organization_id&&m.member_role==='owner'&&m.status==='active').length<=1);
  async function intervene(state){if(!selected||reason.trim().length<5)return;setBusy(true);const{error}=await supabase.rpc('admin_manage_org_member_v2',{p_organization_id:selected.organization_id,p_member_user_id:selected.user_id,p_state:state,p_reason:reason.trim()});setBusy(false);if(error)setNotice(error.message||'Action failed');else{setNotice(ar?'تم التدخل وتسجيل السبب في Audit Log.':'Intervention completed and audited with the reason.');setReason('');setSelected(null);await load();}}
  return <div className="admin-page"><div className="admin-page-heading"><div><span className="admin-kicker"><ShieldCheck size={15}/> IDENTITY & ACCESS</span><h1>{ar?'فرق المنشآت والصلاحيات':'Organization teams & access'}</h1><p>{ar?'رؤية إدارية فقط، مع تدخل محدود ومسبب ومسجل. لا انتحال لحساب العميل ولا تعديل صامت للصلاحيات.':'Administrative visibility with limited, reasoned and audited intervention. No customer impersonation and no silent permission changes.'}</p></div><button className="admin-secondary-button" onClick={load}><RefreshCw className={loading?'spin':''} size={16}/>{ar?'تحديث':'Refresh'}</button></div>{notice&&<div className="admin-care-banner"><ShieldCheck/><span>{notice}</span></div>}<div className="admin-toolbar"><div className="admin-search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?'ابحث عن عضو أو منشأة…':'Search member or organization…'}/></div><select value={org} onChange={e=>setOrg(e.target.value)}><option value="">{ar?'كل المنشآت':'All organizations'}</option>{orgs.map(x=><option key={x.id} value={x.id}>{x.display_name}</option>)}</select></div><div className="admin-table-card"><table><thead><tr><th>{ar?'العضو':'Member'}</th><th>{ar?'المنشأة':'Organization'}</th><th>{ar?'الدور':'Role'}</th><th>MFA</th><th>{ar?'حد الاعتماد':'Approval limit'}</th><th>{ar?'الحالة':'Status'}</th><th>{ar?'الانضمام':'Joined'}</th></tr></thead><tbody>{shown.map(x=>{const p=profiles[x.user_id]||{};return <tr key={`${x.organization_id}:${x.user_id}`} onClick={()=>setSelected(x)} style={{cursor:'pointer'}}><td><strong>{p.full_name||p.email||x.user_id}</strong><small style={{display:'block'}}>{p.email||''}</small></td><td><Building2 size={14}/> {orgMap[x.organization_id]?.display_name||'—'}</td><td>{x.member_role}</td><td>{x.mfa_required?<span className="admin-priority high"><Fingerprint size={12}/> required</span>:'—'}</td><td>{x.approval_limit!=null?Number(x.approval_limit).toLocaleString(ar?'ar-SA':'en-US'):'—'}</td><td><span className={`admin-visibility ${x.status}`}>{x.status}</span></td><td>{fmt(x.joined_at,lang)}</td></tr>})}</tbody></table>{!shown.length&&!loading&&<div className="admin-empty-state"><UsersRound/><strong>{ar?'لا توجد عضويات مطابقة':'No matching memberships'}</strong></div>}</div><div className="admin-info-banner"><FileClock/><span>{ar?'نقل الملكية وإدارة صلاحيات المنشأة تبقى بيد المالك/المدير داخل بوابة العميل. تدخل بلقيس هنا مخصص لتعليق أو إعادة تفعيل الوصول عند الحاجة التشغيلية وبسبب إلزامي.':'Ownership transfer and organization permission design remain with the organization Owner/Manager. Balqees intervention here is limited to suspending/reactivating access with a mandatory reason.'}</span></div>
  {selected&&<div className="admin-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><section className="admin-modal-card access-review"><header><div><small>AUDITED ADMIN INTERVENTION</small><h3>{profiles[selected.user_id]?.full_name||profiles[selected.user_id]?.email||selected.user_id}</h3><p>{orgMap[selected.organization_id]?.display_name} · {selected.member_role}</p></div><button onClick={()=>setSelected(null)}><X/></button></header><div className="admin-access-facts"><span><small>{ar?'الحالة':'Status'}</small><strong>{selected.status}</strong></span><span><small>{ar?'ينتهي الوصول':'Access expiry'}</small><strong>{fmt(selected.access_expires_at,lang)}</strong></span><span><small>{ar?'حد الاعتماد':'Approval limit'}</small><strong>{selected.approval_limit??'—'}</strong></span><span><small>MFA required</small><strong>{selected.mfa_required?'Yes':'No'}</strong></span></div><label>{ar?'سبب التدخل — إلزامي':'Intervention reason — required'}<textarea rows="3" value={reason} onChange={e=>setReason(e.target.value)} placeholder={ar?'مثال: طلب رسمي من مالك المنشأة بعد مغادرة الموظف…':'Example: formal request from the organization owner after employee departure…'}/></label><div className="admin-modal-actions">{selected.status==='active'?<button className="admin-danger-button" disabled={busy||reason.trim().length<5||selectedIsLastOwner} onClick={()=>intervene('suspended')}><UserMinus/>{ar?'تعليق الوصول':'Suspend access'}</button>:<button className="admin-primary-button" disabled={busy||reason.trim().length<5} onClick={()=>intervene('active')}><UserCheck/>{ar?'إعادة التفعيل':'Reactivate'}</button>}</div><div className="admin-audit-mini"><h4><FileClock/>{ar?'آخر تغييرات العضوية':'Recent membership audit'}</h4>{selectedAudit.length?selectedAudit.map(a=><article key={a.id}><strong>{a.action}</strong><span>{fmt(a.created_at,lang)}</span><small>{a.metadata?.reason||''}</small></article>):<p>{ar?'لا يوجد سجل ظاهر لهذه العضوية بعد.':'No visible audit records for this membership yet.'}</p>}</div><div className="admin-care-banner warning"><ShieldAlert/><span>{selectedIsLastOwner?(ar?'هذا هو آخر مالك نشط؛ لا يمكن لبلقيس تعليق وصوله. نقل الملكية Workflow محمي داخل حساب المنشأة.':'This is the last active Owner; Balqees cannot suspend this access. Ownership transfer is protected inside the organization account.'):(ar?'أي تدخل من بلقيس يحتاج سببًا إلزاميًا ويُسجل في Audit Log. نقل الملكية يبقى داخل حساب المنشأة.':'Every Balqees intervention requires a reason and is audited. Ownership transfer remains inside the organization account.')}</span></div></section></div>}
  </div>;
}
