import { useEffect, useMemo, useState } from 'react';
import { Building2, Check, Database, RefreshCw, Settings2, ShieldCheck, X } from 'lucide-react';
import { supabase } from '../../lib/supabase';

const INTEGRATIONS=[['accounting','المحاسبة','Accounting'],['email','البريد','Email'],['erp','ERP','ERP'],['webhook','Webhook','Webhook']];
export default function AdminOrganizationSettings({lang}){
  const ar=lang==='ar';const[orgs,setOrgs]=useState([]);const[orgId,setOrgId]=useState('');const[requests,setRequests]=useState([]);const[settings,setSettings]=useState(null);const[integrations,setIntegrations]=useState([]);const[busy,setBusy]=useState('');const[msg,setMsg]=useState('');
  async function load(){setBusy('load');const o=await supabase.from('organizations').select('id,display_name,legal_name,status').order('display_name');setOrgs(o.data||[]);const selected=orgId||(o.data?.[0]?.id||'');if(!orgId&&selected)setOrgId(selected);if(selected){const [r,s,i]=await Promise.all([supabase.from('organization_change_requests').select('*').eq('organization_id',selected).order('created_at',{ascending:false}),supabase.from('organization_portal_settings').select('*').eq('organization_id',selected).maybeSingle(),supabase.from('organization_integrations').select('*').eq('organization_id',selected).order('integration_key')]);setRequests(r.data||[]);setSettings(s.data||null);setIntegrations(i.data||[]);}setBusy('');}
  useEffect(()=>{load();},[orgId]);
  async function decide(id,decision){const note=window.prompt(ar?'ملاحظة المراجعة (اختياري)':'Review note (optional)')||null;setBusy(id);const{error}=await supabase.rpc('review_organization_change_request_v1',{p_request_id:id,p_decision:decision,p_note:note});setBusy('');if(error){setMsg(error.message);return;}setMsg(ar?'تم تحديث الطلب.':'Request updated.');load();}
  async function setIntegration(key,status){const old=integrations.find(x=>x.integration_key===key)||{};setBusy(key);const{error}=await supabase.from('organization_integrations').upsert({organization_id:orgId,integration_key:key,status,provider_label:old.provider_label||null,public_metadata:old.public_metadata||{},updated_at:new Date().toISOString()},{onConflict:'organization_id,integration_key'});setBusy('');if(error)setMsg(error.message);else load();}
  const org=useMemo(()=>orgs.find(x=>x.id===orgId),[orgs,orgId]);
  return <div className="admin-page admin-org-settings"><header className="admin-page-header"><div><span><Settings2/>{ar?'تجربة بوابة المنشآت':'ORGANIZATION PORTAL EXPERIENCE'}</span><h2>{ar?'إعدادات المنشآت والمراجعات':'Organization settings & reviews'}</h2><p>{ar?'سطح الإدارة المقابل للصفحة 12: طلبات تعديل البيانات الموثقة، سياسة البوابة وحالة التكاملات.':'Admin counterpart for Page 12: verified-data change requests, portal policy and integration status.'}</p></div><button className="admin-secondary-button" onClick={load}><RefreshCw className={busy==='load'?'spin':''}/>{ar?'تحديث':'Refresh'}</button></header>{msg&&<div className="admin-alert">{msg}</div>}<section className="admin-panel"><div className="admin-org-settings-picker"><label>{ar?'المنشأة':'Organization'}<select value={orgId} onChange={e=>setOrgId(e.target.value)}>{orgs.map(x=><option key={x.id} value={x.id}>{x.display_name||x.legal_name}</option>)}</select></label><div><Building2/><span><small>{ar?'الحالة':'Status'}</small><strong>{org?.status||'—'}</strong></span></div><div><ShieldCheck/><span><small>MFA Policy</small><strong>{settings?.mfa_policy||'sensitive_roles'}</strong></span></div></div></section><div className="admin-org-settings-grid"><section className="admin-panel"><header><div><small>VERIFIED DATA</small><h3>{ar?'طلبات تعديل البيانات الموثقة':'Verified data change requests'}</h3></div></header><div className="admin-org-change-list">{requests.length?requests.map(r=><article key={r.id}><div><strong>{r.request_type}</strong><small>{new Date(r.created_at).toLocaleString(ar?'ar-SA':'en-US')} · {r.status}</small><pre>{JSON.stringify(r.requested_changes,null,2)}</pre>{r.reason&&<p>{r.reason}</p>}</div>{['pending','in_review'].includes(r.status)&&<span><button className="admin-primary-button" disabled={busy===r.id} onClick={()=>decide(r.id,'approved')}><Check/>{ar?'اعتماد':'Approve'}</button><button className="admin-secondary-button danger" disabled={busy===r.id} onClick={()=>decide(r.id,'rejected')}><X/>{ar?'رفض':'Reject'}</button></span>}</article>):<div className="admin-empty-state">{ar?'لا توجد طلبات تعديل.':'No change requests.'}</div>}</div></section><section className="admin-panel"><header><div><small>INTEGRATIONS</small><h3>{ar?'حالة التكاملات':'Integration status'}</h3></div></header><div className="admin-org-integration-list">{INTEGRATIONS.map(([k,a,e])=>{const x=integrations.find(v=>v.integration_key===k);return <article key={k}><Database/><div><strong>{ar?a:e}</strong><small>{x?.provider_label|| (ar?'بدون مزود':'No provider')}</small></div><select value={x?.status||'disconnected'} disabled={busy===k} onChange={ev=>setIntegration(k,ev.target.value)}><option value="disconnected">disconnected</option><option value="connected">connected</option><option value="attention">attention</option><option value="disabled">disabled</option></select></article>})}</div></section></div></div>
}
