import { useEffect, useMemo, useState } from 'react';
import { Archive, Building2, CheckCircle2, FileText, MapPin, Plus, RefreshCw, Save, ShieldCheck, Trash2, Upload, Users } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import '../site-admin.css';

const blankArea={name_ar:'',name_en:'',area_type:'lobby',notes_ar:''};
const blankContact={contact_type:'receiving',name:'',role_ar:'',phone:'',email:'',is_primary:false,is_visible:true};
const fmt=(v,lang)=>v?new Intl.DateTimeFormat(lang==='ar'?'ar-SA':'en-GB',{dateStyle:'medium'}).format(new Date(v)):'—';
export default function AdminSites({lang}){
  const ar=lang==='ar'; const[orgs,setOrgs]=useState([]),[rows,setRows]=useState([]),[selected,setSelected]=useState(null),[detail,setDetail]=useState(null),[filterOrg,setFilterOrg]=useState(''),[area,setArea]=useState(blankArea),[contact,setContact]=useState(blankContact),[busy,setBusy]=useState(false),[tab,setTab]=useState('profile');
  async function load(){const[o,s]=await Promise.all([supabase.from('organizations').select('id,display_name,status').order('display_name'),supabase.from('organization_sites').select('*').order('created_at',{ascending:false})]);setOrgs(o.data||[]);setRows(s.data||[])}
  async function openSite(s){setSelected(s);setTab('profile');const[a,c,f,e,contracts,orders]=await Promise.all([supabase.from('organization_site_areas').select('*').eq('site_id',s.id).order('sort_order'),supabase.from('organization_site_contacts').select('*').eq('site_id',s.id).order('sort_order'),supabase.from('organization_site_files').select('*').eq('site_id',s.id).order('created_at',{ascending:false}),supabase.from('organization_site_events').select('*').eq('site_id',s.id).order('created_at',{ascending:false}).limit(40),supabase.from('contract_sites').select('*,contracts(id,contract_number,title_ar,status,ends_on)').eq('site_id',s.id),supabase.from('orders').select('id,order_number,po_number,status,created_at').eq('service_site_id',s.id).order('created_at',{ascending:false}).limit(20)]);setDetail({areas:a.data||[],contacts:c.data||[],files:f.data||[],events:e.data||[],contracts:contracts.data||[],orders:orders.data||[]})}
  useEffect(()=>{load()},[]); const orgMap=useMemo(()=>Object.fromEntries(orgs.map(o=>[o.id,o])),[orgs]); const filtered=rows.filter(s=>!filterOrg||s.organization_id===filterOrg);
  async function saveProfile(ev){ev.preventDefault();const fd=new FormData(ev.currentTarget);const payload={name_ar:fd.get('name_ar'),name_en:fd.get('name_en')||null,site_type:fd.get('site_type'),contact_name:fd.get('contact_name')||null,contact_phone:fd.get('contact_phone')||null,maps_url:fd.get('maps_url')||null,access_notes:fd.get('access_notes')||null,address:{...(selected.address||{}),city:fd.get('city')||'',district:fd.get('district')||'',street:fd.get('street')||'',short_address:(fd.get('short_address')||'').toUpperCase()}};await supabase.from('organization_sites').update(payload).eq('id',selected.id);const updated={...selected,...payload};setSelected(updated);setRows(x=>x.map(r=>r.id===updated.id?updated:r));}
  async function saveAccess(ev){ev.preventDefault();const fd=new FormData(ev.currentTarget);const u=(await supabase.auth.getUser()).data.user;const access={gate_name:fd.get('gate_name')||'',permit_required:fd.get('permit_required')==='on',security_phone:fd.get('security_phone')||'',loading_dock:fd.get('loading_dock')||'',parking_notes:fd.get('parking_notes')||'',access_hours:fd.get('access_hours')||'',elevator_restrictions:fd.get('elevator_restrictions')||'',tools_permit_required:fd.get('tools_permit_required')==='on'};await supabase.from('organization_sites').update({access_details:access,last_verified_at:new Date().toISOString(),last_verified_by:u?.id}).eq('id',selected.id);const updated={...selected,access_details:access,last_verified_at:new Date().toISOString()};setSelected(updated);setRows(x=>x.map(r=>r.id===updated.id?updated:r));}
  async function addArea(ev){ev.preventDefault();await supabase.from('organization_site_areas').insert({...area,organization_id:selected.organization_id,site_id:selected.id,name_ar:area.name_ar.trim(),name_en:area.name_en||null,notes_ar:area.notes_ar||null});setArea(blankArea);await openSite(selected)}
  async function addContact(ev){ev.preventDefault();await supabase.from('organization_site_contacts').insert({...contact,organization_id:selected.organization_id,site_id:selected.id,name:contact.name.trim(),role_ar:contact.role_ar||null,phone:contact.phone||null,email:contact.email||null});setContact(blankContact);await openSite(selected)}
  async function remove(table,id,path){if(path)await supabase.storage.from('organization-site-files').remove([path]);await supabase.from(table).delete().eq('id',id);await openSite(selected)}
  async function upload(ev){const file=ev.target.files?.[0];if(!file)return;setBusy(true);const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-');const path=`${selected.organization_id}/${selected.id}/${Date.now()}-${safe}`;const up=await supabase.storage.from('organization-site-files').upload(path,file);if(!up.error){const u=(await supabase.auth.getUser()).data.user;await supabase.from('organization_site_files').insert({organization_id:selected.organization_id,site_id:selected.id,file_kind:file.type.startsWith('image/')?'image':'document',category:'general',title_ar:file.name,storage_path:path,file_name:file.name,mime_type:file.type,size_bytes:file.size,uploaded_by:u?.id})}setBusy(false);await openSite(selected);ev.target.value=''}
  async function toggleArchive(){const next=!selected.is_active;await supabase.from('organization_sites').update({is_active:next,archived_at:next?null:new Date().toISOString()}).eq('id',selected.id);const updated={...selected,is_active:next};setSelected(updated);setRows(x=>x.map(r=>r.id===updated.id?updated:r));}
  return <div className="admin-page admin-sites-page"><header className="admin-page-head"><div><span>SITE COMMAND CENTER</span><h2>{ar?'المواقع والفروع':'Sites & branches'}</h2><p>{ar?'إدارة مواقع العملاء، مناطق الخدمة، تعليمات الوصول، جهات الاستلام وذاكرة الموقع من مكان واحد.':'Manage client sites, service areas, access, contacts and site memory.'}</p></div><button className="admin-secondary-button" onClick={load}><RefreshCw/>{ar?'تحديث':'Refresh'}</button></header>
    <section className="admin-site-toolbar"><select value={filterOrg} onChange={e=>setFilterOrg(e.target.value)}><option value="">{ar?'كل المنشآت':'All organizations'}</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.display_name}</option>)}</select><span>{filtered.length} {ar?'موقع':'sites'}</span></section>
    <div className="admin-site-layout"><aside className="admin-site-list">{filtered.map(s=><button key={s.id} className={selected?.id===s.id?'active':''} onClick={()=>openSite(s)}><span><Building2/></span><div><strong>{s.name_ar}</strong><small>{orgMap[s.organization_id]?.display_name||'—'} · {s.address?.city||s.site_type}</small></div><em className={s.is_active?'on':'off'}>{s.is_active?(ar?'نشط':'Active'):(ar?'مؤرشف':'Archived')}</em></button>)}</aside>
    <main className="admin-site-detail">{!selected?<div className="admin-site-empty"><MapPin/><strong>{ar?'اختر موقعًا لإدارته':'Select a site to manage'}</strong></div>:<><header className="admin-site-detail-head"><div><small>{orgMap[selected.organization_id]?.display_name}</small><h3>{selected.name_ar}</h3><span>{[selected.address?.city,selected.address?.district,selected.address?.short_address].filter(Boolean).join(' · ')}</span></div><button className="admin-secondary-button" onClick={toggleArchive}><Archive/>{selected.is_active?(ar?'أرشفة':'Archive'):(ar?'إعادة تفعيل':'Reactivate')}</button></header><nav className="admin-site-tabs">{[['profile',ar?'البيانات':'Profile'],['areas',ar?'المناطق':'Areas'],['access',ar?'الوصول':'Access'],['contacts',ar?'الفريق':'Contacts'],['files',ar?'الملفات':'Files'],['timeline',ar?'السجل':'Timeline']].map(([k,l])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{l}</button>)}</nav>
    {tab==='profile'&&<form className="admin-site-form" onSubmit={saveProfile}><label>{ar?'الاسم':'Name'}<input name="name_ar" defaultValue={selected.name_ar} required/></label><label>{ar?'الإنجليزي':'English'}<input name="name_en" defaultValue={selected.name_en||''}/></label><label>{ar?'النوع':'Type'}<input name="site_type" defaultValue={selected.site_type||'branch'}/></label><label>{ar?'المدينة':'City'}<input name="city" defaultValue={selected.address?.city||''}/></label><label>{ar?'الحي':'District'}<input name="district" defaultValue={selected.address?.district||''}/></label><label>{ar?'الشارع':'Street'}<input name="street" defaultValue={selected.address?.street||''}/></label><label>{ar?'العنوان المختصر':'Short address'}<input name="short_address" defaultValue={selected.address?.short_address||''}/></label><label>{ar?'مسؤول الاستلام':'Receiving contact'}<input name="contact_name" defaultValue={selected.contact_name||''}/></label><label>{ar?'الجوال':'Phone'}<input name="contact_phone" defaultValue={selected.contact_phone||''}/></label><label>{ar?'الخريطة':'Maps URL'}<input name="maps_url" defaultValue={selected.maps_url||''}/></label><label className="wide">{ar?'ملاحظات الوصول':'Access notes'}<textarea name="access_notes" defaultValue={selected.access_notes||''}/></label><button className="admin-primary-button"><Save/>{ar?'حفظ':'Save'}</button></form>}
    {tab==='areas'&&<section className="admin-site-section"><form className="admin-site-inline" onSubmit={addArea}><input placeholder={ar?'اسم المنطقة':'Area name'} value={area.name_ar} onChange={e=>setArea({...area,name_ar:e.target.value})} required/><select value={area.area_type} onChange={e=>setArea({...area,area_type:e.target.value})}><option value="lobby">Lobby</option><option value="reception">Reception</option><option value="restaurant">Restaurant</option><option value="garden">Garden</option><option value="office">Office</option><option value="custom">Custom</option></select><input placeholder={ar?'ملاحظة':'Note'} value={area.notes_ar} onChange={e=>setArea({...area,notes_ar:e.target.value})}/><button className="admin-primary-button"><Plus/>{ar?'إضافة':'Add'}</button></form><div className="admin-site-rows">{detail?.areas.map(a=><article key={a.id}><div><strong>{a.name_ar}</strong><small>{a.area_type}</small></div><button onClick={()=>remove('organization_site_areas',a.id)}><Trash2/></button></article>)}</div></section>}
    {tab==='access'&&<form className="admin-site-form" onSubmit={saveAccess}><label>{ar?'البوابة':'Gate'}<input name="gate_name" defaultValue={selected.access_details?.gate_name||''}/></label><label>{ar?'هاتف الأمن':'Security phone'}<input name="security_phone" defaultValue={selected.access_details?.security_phone||''}/></label><label>{ar?'منطقة التحميل':'Loading dock'}<input name="loading_dock" defaultValue={selected.access_details?.loading_dock||''}/></label><label>{ar?'ساعات الدخول':'Access hours'}<input name="access_hours" defaultValue={selected.access_details?.access_hours||''}/></label><label className="wide">{ar?'المواقف':'Parking'}<input name="parking_notes" defaultValue={selected.access_details?.parking_notes||''}/></label><label className="wide">{ar?'قيود المصاعد':'Elevator restrictions'}<input name="elevator_restrictions" defaultValue={selected.access_details?.elevator_restrictions||''}/></label><label className="admin-inline-check"><input name="permit_required" type="checkbox" defaultChecked={Boolean(selected.access_details?.permit_required)}/>{ar?'تصريح دخول':'Entry permit'}</label><label className="admin-inline-check"><input name="tools_permit_required" type="checkbox" defaultChecked={Boolean(selected.access_details?.tools_permit_required)}/>{ar?'تصريح أدوات':'Tools permit'}</label><div className="wide admin-site-verify"><ShieldCheck/><span>{ar?'آخر تأكيد':'Last verified'}: {fmt(selected.last_verified_at,lang)}</span></div><button className="admin-primary-button"><CheckCircle2/>{ar?'حفظ وتأكيد':'Save & verify'}</button></form>}
    {tab==='contacts'&&<section className="admin-site-section"><form className="admin-site-inline contact" onSubmit={addContact}><input placeholder={ar?'الاسم':'Name'} value={contact.name} onChange={e=>setContact({...contact,name:e.target.value})} required/><select value={contact.contact_type} onChange={e=>setContact({...contact,contact_type:e.target.value})}><option value="receiving">Receiving</option><option value="security">Security</option><option value="manager">Manager</option><option value="procurement">Procurement</option><option value="other">Other</option></select><input placeholder={ar?'الدور':'Role'} value={contact.role_ar} onChange={e=>setContact({...contact,role_ar:e.target.value})}/><input placeholder={ar?'الجوال':'Phone'} value={contact.phone} onChange={e=>setContact({...contact,phone:e.target.value})}/><input placeholder={ar?'البريد':'Email'} value={contact.email} onChange={e=>setContact({...contact,email:e.target.value})}/><button className="admin-primary-button"><Plus/>{ar?'إضافة':'Add'}</button></form><div className="admin-site-rows">{detail?.contacts.map(c=><article key={c.id}><div><strong>{c.name}</strong><small>{c.role_ar||c.contact_type} · {c.phone||c.email||'—'}</small></div><button onClick={()=>remove('organization_site_contacts',c.id)}><Trash2/></button></article>)}</div></section>}
    {tab==='files'&&<section className="admin-site-section"><label className="admin-primary-button admin-site-upload"><Upload/>{busy?(ar?'رفع…':'Uploading…'):(ar?'رفع صورة أو ملف':'Upload photo/file')}<input hidden type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={upload}/></label><div className="admin-site-rows">{detail?.files.map(f=><article key={f.id}><div><strong>{f.title_ar||f.file_name}</strong><small>{f.file_kind} · {f.category}</small></div><button onClick={()=>remove('organization_site_files',f.id,f.storage_path)}><Trash2/></button></article>)}</div></section>}
    {tab==='timeline'&&<section className="admin-site-section"><div className="admin-site-timeline">{detail?.events.map(e=><article key={e.id}><i/><div><small>{fmt(e.created_at,lang)}</small><strong>{ar?e.title_ar:(e.title_en||e.title_ar)}</strong><p>{ar?e.body_ar:(e.body_en||e.body_ar)}</p></div></article>)}</div></section>}
    </>}</main></div>
  </div>
}
