import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowUpRight, CheckCircle2, CircleDollarSign, FileText, Link2, RefreshCw, Search, Send, ShieldCheck, Upload, Wallet } from 'lucide-react';
import StatementPreview from './StatementPreview';
import { accountingDate as date, accountingMoney as money, PAYMENT_STATES } from './statementDocument';
import { documentUpload, requestFingerprint, requestIdentity } from './requestIdentity';
import './accounting.css';

const EMPTY={clients:[],links:[],profiles:[],organizations:[],payments:[],statements:[],documents:[]};
export default function AccountingConsole({request,lang='ar',officeMode=false,revision=0}) {
  const ar=lang==='ar',t=(a,e)=>ar?a:e;
  const [data,setData]=useState(EMPTY),[connected,setConnected]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState('payments'),[query,setQuery]=useState('');
  const [selected,setSelected]=useState(''),[kind,setKind]=useState('individual'),[officeId,setOfficeId]=useState(''),[targetId,setTargetId]=useState('');
  const [from,setFrom]=useState(''),[to,setTo]=useState(''),[preview,setPreview]=useState(null),[title,setTitle]=useState(''),[docType,setDocType]=useState('invoice');
  const [paymentFilter,setPaymentFilter]=useState('open');
  const upload=useRef(null),working=useRef(false),sequence=useRef(0);
  const load=useCallback(async()=>{
    const n=++sequence.current;setLoading(true);
    try{const state=await request('state');if(n!==sequence.current)return;setData(state);setConnected(true);setError('');}
    catch(e){if(n!==sequence.current)return;setConnected(false);setData(EMPTY);setPreview(null);setError(e.message);}
    finally{if(n===sequence.current)setLoading(false);}
  },[request]);
  useEffect(()=>{load();return()=>{sequence.current++;};},[load,revision]);
  useEffect(()=>{
    const id=setInterval(()=>{if(document.visibilityState==='visible'&&!working.current)load();},60000);
    return()=>clearInterval(id);
  },[load]);
  const links=useMemo(()=>Object.fromEntries(data.links.map(l=>[l.id,l])),[data.links]);
  const targets=kind==='individual'?data.profiles:data.organizations;
  const targetLabel=x=>kind==='individual'?`${x.full_name||'—'} · ${x.email||x.phone||x.id}`:`${x.display_name||x.legal_name||'—'} · ${x.commercial_number||x.contact_email||x.id}`;
  const activeLinks=data.links.filter(l=>l.is_active);
  const link=links[selected];
  const pending=data.payments.filter(p=>['pending','importing','needs_review'].includes(p.status));
  const payments=data.payments.filter(p=>(paymentFilter==='all'||(paymentFilter==='open'?['pending','importing','needs_review'].includes(p.status):p.status===paymentFilter))&&`${links[p.link_id]?.office_client_name||''} ${p.bank_reference} ${p.amount}`.toLowerCase().includes(query.trim().toLowerCase()));
  async function act(name,fn) {
    if(working.current)return;
    working.current=true;setBusy(name);setError('');setNotice('');
    try{await fn();}catch(e){setError(e.message);}finally{working.current=false;setBusy('');}
  }
  async function publish() {
    if(!link)return;
    if(!window.confirm(t(`إرسال كشف جديد إلى حساب «${link.office_client_name}» وإشعاره داخل الموقع؟ سيُحدَّث الكشف من المكتب وقت الإرسال.`,`Publish a fresh statement to ${link.office_client_name} and notify their account?`)))return;
    await act('publish',async()=>{
      const token=requestIdentity(`statement:${await requestFingerprint(JSON.stringify({selected,from,to}))}`);
      const result=await request('publishStatement',{id:token.id,linkId:selected,from,to});
      token.clear();setPreview(result.payload);setNotice(t('أُرسل الكشف إلى المركز المالي للعميل مع إشعار داخل الموقع.','Statement delivered to the customer financial center with an in-app notification.'));await load();
    });
  }
  async function publishDocument(event) {
    event.preventDefault();
    if(!link||!upload.current?.files?.[0])return;
    if(!window.confirm(t(`إرسال هذا المستند إلى «${link.office_client_name}»؟`,`Send this document to ${link.office_client_name}?`)))return;
    await act('document',async()=>{
      const file=await documentUpload(upload.current.files[0]);
      const token=requestIdentity(`document:${await requestFingerprint(JSON.stringify({selected,title,docType,digest:file.digest}))}`);
      await request('publishDocument',{id:token.id,linkId:selected,title,type:docType,file});
      token.clear();upload.current.value='';setTitle('');setNotice(t('تم إرسال المستند وإشعار العميل.','Document delivered and customer notified.'));await load();
    });
  }
  async function bind(event) {
    event.preventDefault();const client=data.clients.find(c=>c.id===officeId),target=targets.find(c=>c.id===targetId);
    if(!client||!target)return;
    if(!window.confirm(t(`تأكيد الربط:\nعميل المكتب: ${client.name} (${client.client_no||client.id})\nحساب الموقع: ${targetLabel(target)}\n\nسيتمكن هذا الحساب من قراءة ما تنشره له. لا يمكن تغيير الهوية بعد الربط.`,`Confirm linking Office client ${client.name} to ${targetLabel(target)}? The mapping cannot be reassigned.`)))return;
    await act('bind',async()=>{const item=await request('bind',{officeId,kind,targetId});setSelected(item.id);setOfficeId('');setTargetId('');setTab('statements');setNotice(t('تم ربط العميل. يمكنك الآن معاينة كشفه وإرساله.','Client linked. Preview and publish their statement.'));await load();});
  }
  async function review(p) {
    if(p.status==='pending'&&!window.confirm(t(`هل تحققت من استلام مبلغ ${money(p.amount)} ر.س من «${links[p.link_id]?.office_client_name}»؟ سيُسجَّل كحوالة واردة في المكتب.`,`Confirm receipt of SAR ${money(p.amount)}? This records an incoming transfer in Office.`)))return;
    await act(p.id,async()=>{await request('reviewPayment',{id:p.id});setNotice(t('تمت مطابقة الحوالة وتسجيلها في المكتب. أرسل كشفًا جديدًا لإظهار الرصيد المحدث للعميل.','Transfer recorded. Publish a new statement to show the updated balance to the client.'));await load();});
  }
  async function reject(p) {
    const reason=window.prompt(t('سبب عدم اعتماد الإيصال (سيظهر للعميل):','Reason for rejection (visible to the customer):'));
    if(!reason)return;
    await act(p.id,async()=>{await request('rejectPayment',{id:p.id,reason});setNotice(t('تم تحديث الإيصال وإشعار العميل.','Payment proof updated and customer notified.'));await load();});
  }
  async function openFile(action,id) {
    const w=window.open('about:blank','_blank');if(w)w.opener=null;
    await act(`file:${id}`,async()=>{try{const r=await request(action,{id});if(w)w.location.replace(r.url);else throw new Error(t('اسمح بفتح النوافذ لعرض المستند.','Allow popups to view this document.'));}catch(e){w?.close();throw e;}});
  }
  return <section className="acct-console" dir={ar?'rtl':'ltr'}>
    <header className="acct-hero"><div><span className="acct-eyebrow"><ShieldCheck size={16}/> BALQEES · FINANCIAL DESK</span><h1>{t('المكتب المحاسبي','Accounting Office')}</h1><p>{t('كشوف ومستحقات العميل، مستنداته وإيصالاته… في مساحة واحدة.','Customer statements, dues, documents and payment proofs in one place.')}</p><span className={`acct-connection ${connected?'online':''}`}><i/>{loading?t('جارٍ التحقق من الاتصال','Checking connection'):connected?t('الموقع والمكتب متصلان','Site and Office connected'):t('الربط غير متاح حاليًا','Connection unavailable')}</span></div><div className="acct-hero-actions"><a href={officeMode?'/':'https://balqees-smart-office.vercel.app/'} target={officeMode?'_self':'_blank'} rel="noopener noreferrer"><ArrowUpRight size={18}/>{t('فتح المكتب','Open Office')}</a><button onClick={load} disabled={loading||!!busy}><RefreshCw size={17} className={loading?'spin':''}/>{t('تحديث','Refresh')}</button></div></header>
    {error&&<div className="acct-message error" role="alert">{error}{!connected&&<p>{t('لن يُرسل أي كشف أو تُسجّل أي حوالة حتى يكتمل الاتصال.','Statements and transfers are available once the connection is restored.')}</p>}{officeMode&&!connected&&<a href="/">{t('العودة لتسجيل الدخول إلى المكتب','Return to Office sign-in')}</a>}</div>}
    {notice&&<div className="acct-message success" role="status"><CheckCircle2 size={18}/>{notice}</div>}
    <div className="acct-metrics"><article><Link2/><div><small>{t('حسابات مرتبطة','Linked accounts')}</small><strong>{connected?data.links.length:"—"}</strong></div></article><article><Wallet/><div><small>{t('إيصالات للمراجعة','Proofs to review')}</small><strong>{connected?pending.length:"—"}</strong></div></article><article><FileText/><div><small>{t('كشوف مرسلة • آخر 100','Published statements · latest 100')}</small><strong>{connected?data.statements.length:"—"}</strong></div></article></div>
    <nav className="acct-tabs" aria-label={t('أقسام المحاسبة','Accounting sections')}>{[['payments','إيصالات السداد','Payment proofs'],['statements','الكشوف والمستندات','Statements & documents'],['links','ربط العملاء','Client mapping']].map(([key,a,e])=><button key={key} aria-current={tab===key?'page':undefined} onClick={()=>setTab(key)}>{t(a,e)}{key==='payments'&&pending.length>0&&<b>{pending.length}</b>}</button>)}</nav>
    {tab==='payments'&&<div className="acct-card"><header><div><h2>{t('وارد العملاء','Customer inbox')}</h2><p>{t('رفع الإيصال لا يؤكد السداد. راجعه قبل اعتماده في المكتب.','A proof upload does not confirm receipt. Verify it before recording it in Office.')}</p></div><span className="acct-muted">{t('آخر 250 إيصالًا','Latest 250 proofs')}</span></header><div className="acct-toolbar"><label className="acct-search"><Search size={17}/><input aria-label={t('البحث في الإيصالات','Search proofs')} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('اسم العميل، مرجع الحوالة أو المبلغ','Client, reference or amount')}/></label><select aria-label={t('حالة الإيصال','Payment status')} value={paymentFilter} onChange={e=>setPaymentFilter(e.target.value)}><option value="open">{t('تحتاج متابعة','Needs attention')}</option><option value="recorded">{t('مسجلة في المكتب','Recorded')}</option><option value="rejected">{t('لم تُعتمد','Rejected')}</option><option value="all">{t('الكل','All')}</option></select></div><div className="acct-inbox">{payments.map(p=><article key={p.id}><div className="acct-payment-title"><span className="acct-item-icon"><Wallet size={20}/></span><div><h3>{links[p.link_id]?.office_client_name||'—'}</h3><p><bdi>{p.bank_reference}</bdi> · <bdi>{date(p.payment_date)}</bdi></p></div><strong className="acct-amount" dir="ltr">{money(p.amount)} <small>SAR</small></strong></div><div className="acct-payment-details"><span className={`acct-status ${p.status}`}>{PAYMENT_STATES[p.status]?.[ar?0:1]||p.status}</span><span>{t('الطريقة: ','Method: ')}{({bank_transfer:t('تحويل بنكي','Bank transfer'),card:t('بطاقة','Card'),cash:t('نقدي','Cash')})[p.payment_method]}</span>{p.note&&<p>{p.note}</p>}{p.review_note&&<p>{p.review_note}</p>}{p.office_transfer_id&&<small dir="ltr">{p.office_transfer_id}</small>}</div><div className="acct-actions"><button disabled={!!busy||!connected} onClick={()=>openFile('proof',p.id)}><FileText size={16}/>{t('عرض الإيصال','View proof')}</button>{['pending','importing','needs_review'].includes(p.status)&&<button className="acct-primary" disabled={!!busy||!connected} onClick={()=>review(p)}><CheckCircle2 size={16}/>{p.status==='pending'?t('اعتماد وتسجيل حوالة','Approve & record'):t('التحقق من تسجيل الحوالة','Reconcile transfer')}</button>}{p.status==='pending'&&<button className="acct-danger" disabled={!!busy||!connected} onClick={()=>reject(p)}>{t('عدم الاعتماد','Reject')}</button>}</div></article>)}{!payments.length&&<div className="acct-empty"><Wallet/><h3>{loading?t('جارٍ التحميل…','Loading…'):t('لا توجد إيصالات في هذه القائمة','No proofs in this list')}</h3><p>{t('إيصالات العملاء المرتبطين تظهر هنا عند رفعها من مركزهم المالي.','Proofs from linked customers appear here when uploaded in their financial center.')}</p></div>}</div></div>}
    {tab==='statements'&&<><div className="acct-card"><header><div><h2>{t('إرسال للعميل','Deliver to customer')}</h2><p>{t('الكشف نسخة محفوظة بتاريخ إعداده. كل إرسال جديد يُحفظ في سجل العميل.','Each statement is a dated snapshot. Every new publication remains in the customer history.')}</p></div></header><div className="acct-form-grid"><label>{t('حساب العميل المرتبط','Linked customer')}<select value={selected} onChange={e=>{setSelected(e.target.value);setPreview(null);}} disabled={!!busy}><option value="">{t('اختر العميل','Choose a client')}</option>{activeLinks.map(l=><option key={l.id} value={l.id}>{l.office_client_name} · {l.organization_id?t('منشأة','Organization'):t('فرد','Individual')} · {l.id.slice(-6)}</option>)}</select></label><label>{t('من تاريخ (اختياري)','From (optional)')}<input type="date" value={from} onChange={e=>setFrom(e.target.value)} disabled={!!busy}/></label><label>{t('إلى تاريخ (اختياري)','To (optional)')}<input type="date" value={to} min={from||undefined} onChange={e=>setTo(e.target.value)} disabled={!!busy}/></label></div><div className="acct-actions"><button disabled={!link||!connected||!!busy} onClick={()=>act('preview',async()=>setPreview(await request('preview',{linkId:selected,from,to})))}><FileText size={16}/>{t('معاينة الكشف والمستحقات','Preview statement & dues')}</button><button className="acct-primary" disabled={!link||!connected||!!busy} onClick={publish}><Send size={16}/>{t('إرسال كشف للعميل','Send statement to customer')}</button></div><p className="acct-muted">{t('يصل الإرسال داخل حساب العميل مع إشعار في الموقع.','Delivered to the customer account with an in-app notification.')}</p></div>
    <div className="acct-split"><form className="acct-card" onSubmit={publishDocument}><header><div><h2>{t('إرفاق مستند مالي','Attach a financial document')}</h2><p>{link?t(`إلى: ${link.office_client_name}`,`To: ${link.office_client_name}`):t('اختر العميل من الأعلى أولًا.','Choose a customer above first.')}</p></div><Upload size={23}/></header><fieldset disabled={!link||!connected||!!busy}><label>{t('عنوان المستند','Document title')}<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)} placeholder={t('مثال: فاتورة توريد شهر أكتوبر','Example: October supply invoice')}/></label><label>{t('النوع','Type')}<select value={docType} onChange={e=>setDocType(e.target.value)}>{[['invoice','فاتورة','Invoice'],['receipt','سند قبض','Receipt'],['statement','كشف','Statement'],['credit_note','إشعار دائن','Credit note'],['debit_note','إشعار مدين','Debit note'],['other','مستند آخر','Other']].map(([v,a,e])=><option key={v} value={v}>{t(a,e)}</option>)}</select></label><label>{t('الملف · PDF أو صورة · حتى 3 MB','File · PDF or image · up to 3 MB')}<input ref={upload} type="file" required accept="application/pdf,image/png,image/jpeg,image/webp"/></label><button className="acct-primary" type="submit"><Send size={16}/>{t('إرسال المستند','Send document')}</button></fieldset></form>
    <div className="acct-card"><header><div><h2>{t('سجل الإرسال','Delivery history')}</h2><p>{t('آخر 100 كشف و100 مستند. اختر العميل لتصفية السجل.','Latest 100 statements and 100 documents. Choose a customer to filter.')}</p></div></header><div className="acct-history">{data.statements.filter(s=>!selected||s.link_id===selected).map(s=><button key={s.id} disabled={!!busy||!connected} onClick={()=>act(`statement:${s.id}`,async()=>setPreview(await request('getStatement',{id:s.id})))}><FileText size={18}/><span><strong>{links[s.link_id]?.office_client_name}</strong><small><bdi>{s.statement_number}</bdi> · {date(s.created_at)}</small></span><ArrowUpRight size={17}/></button>)}{data.documents.filter(d=>!selected||d.link_id===selected).map(d=><button key={d.id} disabled={!!busy||!connected} onClick={()=>openFile('document',d.id)}><FileText size={18}/><span><strong>{d.title}</strong><small>{links[d.link_id]?.office_client_name} · {date(d.created_at)}</small></span><ArrowUpRight size={17}/></button>)}{!data.statements.length&&!data.documents.length&&<p className="acct-empty">{t('لا توجد إرسالات بعد.','No deliveries yet.')}</p>}</div></div></div></>}
    {tab==='links'&&<div className="acct-split"><form className="acct-card" onSubmit={bind}><header><div><h2>{t('ربط حساب عميل','Link a customer account')}</h2><p>{t('راجع رقم العميل وبيانات الحساب قبل التأكيد. الربط يحدد من يستلم مستنداته المالية.','Verify the client reference and account details. This mapping determines who receives financial documents.')}</p></div><Link2 size={23}/></header><fieldset disabled={!connected||!!busy}><label>{t('عميل المكتب','Office client')}<select required value={officeId} onChange={e=>setOfficeId(e.target.value)}><option value="">{t('اختر من سجل المكتب','Choose from Office')}</option>{data.clients.filter(c=>!data.links.some(l=>l.office_client_id===c.id)).map(c=><option key={c.id} value={c.id}>{c.name} · {c.client_no||c.id}</option>)}</select></label><label>{t('نوع حساب الموقع','Site account type')}<select value={kind} onChange={e=>{setKind(e.target.value);setTargetId('');}}><option value="individual">{t('فرد','Individual')}</option><option value="organization">{t('منشأة','Organization')}</option></select></label><label>{t('حساب العميل في الموقع','Customer account on site')}<select required value={targetId} onChange={e=>setTargetId(e.target.value)}><option value="">{t('اختر الحساب المطابق','Choose the matching account')}</option>{targets.filter(x=>!data.links.some(l=>l.user_id===x.id||l.organization_id===x.id)).map(x=><option key={x.id} value={x.id}>{targetLabel(x)}</option>)}</select></label><button type="submit" className="acct-primary"><Link2 size={16}/>{t('مراجعة وتأكيد الربط','Review & confirm mapping')}</button></fieldset></form><div className="acct-card"><header><div><h2>{t('الحسابات المرتبطة','Linked accounts')}</h2><p>{t('كل حساب مرتبط بعميل واحد في المكتب.','Each account maps to one Office client.')}</p></div></header><div className="acct-history">{data.links.map(l=><button key={l.id} onClick={()=>{setSelected(l.id);setTab('statements');}}><span className="acct-item-icon"><CircleDollarSign size={20}/></span><span><strong>{l.office_client_name}</strong><small>{l.organization_id?t('منشأة','Organization'):t('فرد','Individual')} · <bdi>{l.office_client_id}</bdi></small></span><span className="acct-status recorded">{l.is_active?t('نشط','Active'):t('موقوف','Inactive')}</span></button>)}{!data.links.length&&<p className="acct-empty">{t('ابدأ بربط أول عميل.','Link your first client.')}</p>}</div></div></div>}
    {busy&&<div className="acct-working" role="status"><RefreshCw className="spin" size={16}/>{t('جارٍ إكمال العملية…','Completing operation…')}</div>}
    {preview&&<StatementPreview report={preview} onClose={()=>setPreview(null)} lang={lang}/>}
  </section>;
}
