import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowDownToLine, ArrowUpRight, Building2, ClipboardList, FileText, Package, RefreshCw, Search, Send } from 'lucide-react';
import { accountingDate as date, accountingMoney as money } from './statementDocument';
import { requestFingerprint, requestIdentity } from './requestIdentity';

const TYPES=[['orders','طلبات المتجر','Store orders',Package],['rfq','طلبات عرض السعر','Quote requests',ClipboardList],['requests','طلبات المنشآت','Organization requests',Building2],['quotations','عروض المنشآت','Organization quotations',FileText],['contracts','العقود','Contracts',FileText]];
const STATUS={pending:['تم الاستلام','Received'],submitted:['تم الإرسال','Submitted'],in_review:['قيد المراجعة','In review'],under_review:['قيد المراجعة','In review'],needs_info:['تحتاج معلومات','Needs information'],quoted:['تم التسعير','Quoted'],closed:['مغلق','Closed'],approved:['معتمد','Approved'],in_progress:['قيد التجهيز','Preparing'],ready:['جاهز','Ready'],out_for_delivery:['في الطريق','Out for delivery'],delivered:['تم التسليم','Delivered'],delivery_failed_payment:['تعثر التسليم أو السداد','Delivery or payment issue'],completed:['مكتمل','Completed'],cancelled:['ملغى','Cancelled'],converted:['تم التحويل','Converted'],sent:['مرسل','Sent'],viewed:['تم الاطلاع','Viewed'],accepted:['مقبول','Accepted'],declined:['مرفوض','Declined'],revision_requested:['طلب تعديل','Revision requested'],active:['ساري','Active'],expiring:['قرب الانتهاء','Expiring'],expired:['منتهي','Expired'],terminated:['معلق','Terminated']};
const STATES={orders:['pending','under_review','quoted','approved','in_progress','ready','out_for_delivery','delivered','delivery_failed_payment','completed','cancelled'],rfq:['in_review','needs_info','quoted','closed'],requests:['under_review','needs_info','converted','cancelled']};
const PATH={orders:'/admin/orders?order=',rfq:'/admin/quote-requests?request=',requests:'/admin/service-requests',quotations:'/admin/quotes',contracts:'/admin/contracts'};
const empty={rows:[],jobs:[],profiles:[],organizations:[],offset:0,more:false};
const reference=(kind,r)=>({orders:`BLQ #${r.order_number}`,rfq:`RFQ #${r.request_number}`,requests:r.request_code,quotations:`Q #${r.quote_number} · V${r.version_number||1}`,contracts:r.contract_number})[kind];
function matches(r,l){return l.is_active&&(r.organization_id?l.organization_id===r.organization_id:!!r.user_id&&l.user_id===r.user_id);}

export default function OfficeOperations({request,links=[],payments=[],lang='ar',connected=true,onFinance,onMapping,revision=0}) {
  const ar=lang==='ar',t=(a,e)=>ar?a:e,label=s=>STATUS[s]?.[ar?0:1]||s;
  const [kind,setKind]=useState('orders'),[page,setPage]=useState(0),[data,setData]=useState(empty),[detail,setDetail]=useState(null);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState('');
  const [form,setForm]=useState({status:'',reply:'',amount:'',vatRate:15,validUntil:'',note:''});
  const [paymentId,setPaymentId]=useState('');
  const sequence=useRef(0),working=useRef(false),detailSequence=useRef(0),detailRef=useRef(null);
  const load=useCallback(async()=>{
    const seq=++sequence.current;setLoading(true);
    try {const result=await request('operations',{kind,offset:page*50});if(seq===sequence.current){setData({...empty,...result});setError('');}}
    catch(e){if(seq===sequence.current){setData(empty);setError(e.message);}}
    finally{if(seq===sequence.current)setLoading(false);}
  },[request,kind,page]);
  useEffect(()=>{setDetail(null);detailSequence.current++;load();return()=>{sequence.current++;};},[load]);
  useEffect(()=>{if(revision&&!working.current)load();},[revision,load]);
  useEffect(()=>{const id=setInterval(()=>{if(document.visibilityState==='visible'&&!working.current)load();},60000);return()=>clearInterval(id);},[load]);
  async function choose(row) {
    const seq=++detailSequence.current;setError('');setNotice('');setDetail(null);setPaymentId('');
    try {const result=await request('operation',{kind,id:row.id});if(seq!==detailSequence.current)return;setDetail(result);
      const r=result.source;setForm({status:r.status==='submitted'?(kind==='rfq'?'in_review':'under_review'):r.status,reply:r.admin_reply||r.description||'',amount:r.quote_amount??'',vatRate:15,validUntil:r.quote_valid_until||'',note:r.admin_note||''});
      requestAnimationFrame(()=>detailRef.current?.focus({preventScroll:true}));
    } catch(e){if(seq===detailSequence.current)setError(e.message);}
  }
  const source=detail?.source,link=source?links.find(l=>matches(source,l)):null;
  const run=async fn=>{if(working.current)return;working.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e.message);}finally{working.current=false;setBusy(false);}};
  async function update(e) {
    e.preventDefault();if(!source)return;
    await run(async()=>{const input={kind,id:source.id,...form,expectedUpdatedAt:source.updated_at};
      const token=requestIdentity(`operation:${await requestFingerprint(JSON.stringify(input))}`);
      const saved=await request('updateOperation',{...input,commandId:token.id});token.clear();setDetail(d=>({...d,source:saved}));
      setNotice(t('تم حفظ التحديث في الموقع وإشعار العميل.','Website updated and customer notified.'));await load();});
  }
  async function importRecord() {
    if(!source||!link)return;
    if(!window.confirm(t(`استيراد ${reference(kind,source)} إلى سجل «${link.office_client_name}» في المكتب؟`,'Import this record into the linked Office customer account?')))return;
    await run(async()=>{try{const job=await request('importOperation',{kind,id:source.id,linkId:link.id,vatRate:form.vatRate});setDetail(d=>({...d,job}));setNotice(t('تمت مطابقة السجل وحفظه في المكتب.','Record reconciled and saved in Office.'));await load();}catch(e){const latest=await request('operation',{kind,id:source.id}).catch(()=>null);if(latest)setDetail(latest);throw e;}});
  }
  async function quoteOrganization(e) {
    e.preventDefault();if(!source)return;
    if(!window.confirm(t('إرسال هذا العرض إلى بوابة المنشأة؟ سيظهر للعميل نطاق العرض والإجمالي شامل الضريبة.','Send this quotation with its scope and VAT-inclusive total to the organization portal?')))return;
    await run(async()=>{const input={id:source.id,...form,expectedUpdatedAt:source.updated_at};const token=requestIdentity(`org-quote:${await requestFingerprint(JSON.stringify(input))}`);
      const quote=await request('createOrganizationQuote',{...input,commandId:token.id});token.clear();
      const current=await request('operation',{kind,id:source.id});setDetail(current);setNotice(t(`أُرسل العرض #${quote.quote_number} إلى بوابة المنشأة، ويمكن استيراده من تبويب عروض المنشآت.`,`Quotation #${quote.quote_number} sent. Import it from the organization quotations tab.`));await load();});
  }
  async function applyPayment(e) {
    e.preventDefault();if(!source||!paymentId)return;
    if(!window.confirm(t('تأكيد تخصيص هذا الإيصال المعتمد لهذا الطلب؟ لن يمكن استخدامه لسداد طلب آخر.','Allocate this verified proof to this order? The proof cannot pay another order.')))return;
    await run(async()=>{const updated=await request('applyOrderPayment',{id:source.id,paymentId,expectedUpdatedAt:source.updated_at});setDetail(d=>({...d,source:updated}));setPaymentId('');setNotice(t('تم ربط الحوالة المسجلة بالطلب واعتماد سداده.','Recorded Office transfer linked and order payment verified.'));await load();});
  }
  const job=detail?.job,closed=source&&['completed','cancelled','closed','converted','draft'].includes(source.status);
  const visible=data.rows.filter(r=>`${reference(kind,r)} ${r.contact_name||''} ${r.description||''} ${r.title_ar||''} ${data.profiles.find(p=>p.id===r.user_id||p.id===r.created_by)?.full_name||''} ${data.organizations.find(o=>o.id===r.organization_id)?.display_name||''}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <div className="office-operations">
    <div className="acct-card"><header><div><h2>{t('وارد الموقع ومتابعة التنفيذ','Website inbox & fulfillment')}</h2><p>{t('راجع الطلب، حدّث العميل، ثم استورد سجل العمل إلى المكتب. الكشوف والسداد في الأقسام المالية.','Review requests, update customers and import operational records into Office. Statements and payments are in the financial sections.')}</p></div><button disabled={busy||loading||!connected} onClick={load}><RefreshCw size={16}/>{t('تحديث الوارد','Refresh inbox')}</button></header>
      <div className="office-source-tabs" role="group" aria-label={t('نوع الطلب','Request type')}>{TYPES.map(([key,a,e,Icon])=><button key={key} aria-pressed={kind===key} disabled={busy} onClick={()=>{setKind(key);setPage(0);setQuery('');}}><Icon size={16}/>{t(a,e)}</button>)}</div>
      <label className="acct-search"><Search size={17}/><input aria-label={t('بحث في صفحة الوارد','Search inbox page')} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('رقم الطلب أو اسم العميل…','Reference or customer…')}/></label>
    </div>
    {error&&<div role="alert" className="acct-message error">{error}</div>}{notice&&<div role="status" className="acct-message success">{notice}</div>}
    <div className="office-inbox-grid"><div className="acct-card office-source-list"><div className="acct-history">{visible.map(r=>{const p=data.profiles.find(p=>p.id===(r.user_id||r.created_by)),o=data.organizations.find(o=>o.id===r.organization_id),j=data.jobs.find(j=>j.source_id===r.id);return <button key={r.id} disabled={busy||!connected} aria-current={source?.id===r.id?'true':undefined} onClick={()=>choose(r)}><span><strong>{reference(kind,r)}</strong><small>{o?.display_name||o?.legal_name||r.contact_name||p?.full_name||'—'}</small><small>{date(r.created_at)} · {label(r.status)}</small>{j&&<small className={j.status==='recorded'?'office-imported':'office-review'}>{j.status==='recorded'?t('مستورد إلى المكتب','Imported into Office'):t('استيراد يحتاج متابعة','Import needs attention')}</small>}</span><ArrowUpRight size={16}/></button>;})}{!visible.length&&<p className="acct-empty">{loading?t('تحميل الوارد…','Loading inbox…'):t('لا توجد سجلات في هذه الصفحة.','No records on this page.')}</p>}</div><div className="office-pagination"><button disabled={!page||busy||loading} onClick={()=>setPage(p=>p-1)}>{t('السابق','Previous')}</button><small>{t('صفحة','Page')} {page+1}</small><button disabled={!data.more||busy||loading} onClick={()=>setPage(p=>p+1)}>{t('التالي','Next')}</button></div></div>
    <section className="acct-card office-source-detail" ref={detailRef} tabIndex={-1} aria-label={t('تفاصيل الطلب','Request details')}>{source?<>
      <header><div><small className="acct-muted">{reference(kind,source)}</small><h2>{source.title_ar||source.contact_name||TYPES.find(x=>x[0]===kind)?.[ar?1:2]}</h2><p>{label(source.status)} · {date(source.created_at)}</p></div><a className="office-site-link" target="_blank" rel="noopener noreferrer" href={`https://balqeesfloral.vercel.app${PATH[kind]}${['orders','rfq'].includes(kind)?source.id:''}`}><ArrowUpRight size={16}/>{t('تفاصيل الموقع','Website details')}</a></header>
      <dl className="office-details"><dt>{t('حساب المكتب','Office account')}</dt><dd>{link?.office_client_name||t('لم يُربط بعد','Not linked yet')}</dd>{(source.phone||source.email)&&<><dt>{t('التواصل','Contact')}</dt><dd><bdi>{source.phone||source.email}</bdi></dd></>}{(source.location||source.service_address?.city||source.address_snapshot?.city)&&<><dt>{t('الموقع','Location')}</dt><dd>{source.location||source.service_address?.city||source.address_snapshot?.city}</dd></>}{(source.total!=null||source.quote_amount!=null||detail.financial?.contract_value!=null)&&<><dt>{t('الإجمالي (ر.س)','Total (SAR)')}</dt><dd><bdi>{money(source.total??source.quote_amount??detail.financial?.contract_value)}</bdi></dd></>}{source.payment_status&&<><dt>{t('حالة السداد في الموقع','Website payment status')}</dt><dd>{source.payment_status==='paid'?t('مسدد في الموقع','Paid on website'):t('السداد لم يُؤكد','Payment unconfirmed')}</dd></>}</dl>
      {(source.description||source.customer_note||source.services_summary_ar)&&<p className="office-brief">{source.description||source.customer_note||source.services_summary_ar}</p>}
      {!!(detail.items?.length||source.product_snapshot?.length)&&<div className="office-lines">{(detail.items?.length?detail.items:source.product_snapshot).map((x,i)=><p key={x.id||x.product_id||i}><span>{x.description_ar||x.product_snapshot?.name_ar||x.name_ar||'—'}</span><b><bdi>{x.quantity}</bdi> {t('وحدة','units')}</b></p>)}</div>}
      {link?<div className="acct-actions"><button className="acct-primary" disabled={busy||!connected||job?.status==='recorded'||(['rfq'].includes(kind)&&source.status!=='quoted')} onClick={importRecord}><ArrowDownToLine size={16}/>{job?.status==='recorded'?t('مستورد إلى المكتب','Imported into Office'):job?t('مطابقة الاستيراد','Reconcile import'):t('استيراد إلى المكتب','Import into Office')}</button><button disabled={busy} onClick={()=>onFinance(link.id)}>{t('كشف ومستندات العميل','Customer statements & documents')}</button></div>:<div className="acct-message"><p>{t('اربط حساب العميل قبل استيراد السجل أو إرسال مستنداته.','Map the customer before importing records or sending documents.')}</p><button onClick={onMapping}>{t('ربط العملاء','Client mapping')}</button></div>}
      {kind==='rfq'&&<label className="office-vat">{t('نسبة الضريبة عند الاستيراد إلى المكتب (%)','VAT rate for Office import (%)')}<input type="number" min="0" max="100" step="0.01" value={form.vatRate} onChange={e=>setForm(f=>({...f,vatRate:e.target.value}))}/><small>{t('إجمالي العرض يشمل هذه الضريبة؛ راجع النسبة حسب العرض المتفق عليه.','The quote total includes this VAT. Verify the rate against the agreed quotation.')}</small></label>}
      {job&&<p className="acct-muted">{job.status==='recorded'?t('سجل المكتب يحفظ بيانات وقت الاستيراد. يمكنك متابعة أحدث حالة الطلب هنا.','Office stores the imported snapshot. Follow the latest request status here.'):t('تحقق من السجل الموجود عند انقطاع الاتصال. لن تُضف نسخة ثانية.','Reconcile existing records after a connection interruption. No second copy is appended.')}</p>}
      {STATES[kind]&&!closed&&<form className="office-update-form" onSubmit={update}><h3>{t('تحديث العميل من المكتب','Update the customer from Office')}</h3><fieldset disabled={busy||!connected}><label>{t('الحالة','Status')}<select required value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value}))}>{STATES[kind].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label>{kind==='rfq'&&<><label>{t('الرد ونطاق العرض','Reply & quotation scope')}<textarea rows="4" maxLength={4000} required={['quoted','needs_info'].includes(form.status)} value={form.reply} onChange={e=>setForm(f=>({...f,reply:e.target.value}))}/></label>{form.status==='quoted'&&<PriceFields form={form} setForm={setForm} t={t}/>}</>}{kind==='orders'&&<label>{t('ملاحظة داخلية','Internal note')}<textarea maxLength={4000} rows="3" value={form.note} onChange={e=>setForm(f=>({...f,note:e.target.value}))}/></label>}<button className="acct-primary"><Send size={16}/>{t('حفظ وإشعار العميل','Save & notify customer')}</button></fieldset></form>}
      {kind==='orders'&&link&&!closed&&source.payment_status!=='paid'&&<form className="office-update-form" onSubmit={applyPayment}><h3>{t('اعتماد سداد الطلب','Verify order payment')}</h3><p className="acct-muted">{t('اختر إيصالًا مسجلًا في المكتب لنفس العميل وبنفس إجمالي الطلب. الإيصال الواحد يسدد طلبًا واحدًا.','Choose a recorded Office proof for the same customer and exact order total. A proof can pay one order.')}</p><fieldset disabled={busy||!connected}><label>{t('الإيصال المعتمد','Verified payment proof')}<select required value={paymentId} onChange={e=>setPaymentId(e.target.value)}><option value="">{t('اختر إيصال السداد','Choose a payment proof')}</option>{payments.filter(p=>p.status==='recorded'&&p.link_id===link.id&&Number(p.amount)===Number(source.total)).map(p=><option value={p.id} key={p.id}>{p.bank_reference} · {money(p.amount)} · {date(p.payment_date)}</option>)}</select></label><button className="acct-primary" disabled={!paymentId}>{t('ربط الإيصال واعتماد سداد الطلب','Allocate proof & verify order payment')}</button></fieldset></form>}
      {kind==='requests'&&!closed&&<form className="office-update-form" onSubmit={quoteOrganization}><h3>{t('إرسال عرض إلى المنشأة','Send an organization quotation')}</h3><fieldset disabled={busy||!connected}><label>{t('نطاق العرض وشروطه','Scope & terms')}<textarea required minLength={3} maxLength={4000} rows="4" value={form.reply} onChange={e=>setForm(f=>({...f,reply:e.target.value}))}/></label><PriceFields form={form} setForm={setForm} t={t}/><label>{t('نسبة الضريبة (%)','VAT rate (%)')}<input required type="number" min="0" max="100" step="0.01" value={form.vatRate} onChange={e=>setForm(f=>({...f,vatRate:e.target.value}))}/></label><button className="acct-primary"><Send size={16}/>{t('إرسال العرض إلى بوابة المنشأة','Send quotation to organization portal')}</button></fieldset></form>}
    </>:<div className="acct-empty"><ClipboardList/><h3>{t('اختر سجلًا من الوارد','Choose an inbox record')}</h3><p>{t('تفاصيل الموقع وحالة الاستيراد والمتابعة تظهر هنا.','Website details, import status and follow-up appear here.')}</p></div>}</section></div>
  </div>;
}
function PriceFields({form,setForm,t}) {return <div className="office-price-fields"><label>{t('الإجمالي شامل الضريبة (ر.س)','Total including VAT (SAR)')}<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm(f=>({...f,amount:e.target.value}))}/></label><label>{t('صالح حتى (اختياري)','Valid until (optional)')}<input type="date" value={form.validUntil} onChange={e=>setForm(f=>({...f,validUntil:e.target.value}))}/></label></div>;}
