const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const accountingMoney = value => new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value || 0));
export const accountingDate = value => String(value || '').slice(0,10) || '—';
export const PAYMENT_STATES = {
  pending:['بانتظار المراجعة','Awaiting review'],importing:['جارٍ التحقق من التسجيل','Verifying ledger entry'],
  needs_review:['تحتاج مطابقة في المكتب','Needs ledger reconciliation'],recorded:['مسجل في المكتب','Recorded in Office'],rejected:['لم يُعتمد','Not approved'],
};
export function statementDocument(report) {
  const e = escape,m = accountingMoney,s = report.summary || {},cl = report.client || {},c = report.company || {};
  const metric = (label,value) => `<div><small>${label}</small><strong dir="ltr">${m(value)} <small>SAR</small></strong></div>`;
  return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>كشف حساب ${e(cl.name)}</title><style>
  *{box-sizing:border-box}body{margin:0;padding:28px;font:13px/1.8 Tahoma,Arial,sans-serif;color:#283926;background:#fff}header{display:flex;justify-content:space-between;gap:24px;padding-bottom:22px;border-bottom:3px solid #b39959}header img{width:120px;object-fit:contain}h1{font-size:25px;margin:4px 0}p{margin:4px 0}small{color:#617060}strong{display:block}.meta{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:20px 0}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.metrics>div{background:#f2f3ed;border:1px solid #dce2d4;border-radius:10px;padding:14px}.metrics strong{font-size:18px}table{border-collapse:collapse;width:100%;font-size:11px;margin:14px 0}th{background:#2c442d;color:#fff}th,td{padding:9px 6px;border-bottom:1px solid #dde3d8;text-align:right;overflow-wrap:anywhere}td.num{text-align:left;direction:ltr;white-space:nowrap}h2{font-size:17px;margin-top:24px}footer{border-top:1px solid #b39959;margin-top:22px;padding-top:12px;color:#617060}.wm{position:fixed;inset:25% 15%;opacity:.025;width:70%;height:50%;object-fit:contain;pointer-events:none;z-index:-1}.fine{color:#617060;font-size:11px}tr{break-inside:avoid}thead{display:table-header-group}@page{size:A4 landscape;margin:12mm}@media print{body{padding:0;font-size:11px}.metrics>div,th{-webkit-print-color-adjust:exact;print-color-adjust:exact}h2{break-after:avoid}}@media(max-width:600px){body{padding:14px}.metrics{grid-template-columns:1fr 1fr}header{gap:10px}header img{width:80px}.scroll{overflow:auto}table{min-width:650px}}
  </style></head><body><img class="wm" alt="" src="https://balqees123.vercel.app/assets/brand/balqees-logo.webp"><header><div><small>BALQEES · CLIENT STATEMENT</small><h1>كشف حساب العميل</h1><p>${e(c.company_name || 'مؤسسة بلقيس')}</p><p dir="ltr">${e(report.statementNo)}</p></div><img src="https://balqees123.vercel.app/assets/brand/balqees-logo.webp" alt="بلقيس"></header>
  <div class="meta"><div><small>العميل</small><strong>${e(cl.name)}</strong><p>${e(cl.client_no)}${cl.vat_no ? ' · الرقم الضريبي: '+e(cl.vat_no) : ''}</p></div><div><small>الفترة</small><strong>${e(report.filters?.from || 'من بداية الحساب')} — ${e(report.filters?.to || '—')}</strong><p>أُعدّ في: <b dir="ltr">${e(report.generatedAt?.replace('T',' ').slice(0,19))}</b></p></div></div>
  <div class="metrics">${metric('الرصيد الافتتاحي',s.openingBalance)}${metric('المستحقات خلال الفترة',s.totalReceivables)}${metric('السداد خلال الفترة',s.totalPayments)}${metric(Number(s.closingBalance)<0?'رصيد دائن للعميل':'الرصيد المتبقي',s.closingBalance)}</div>
  <h2>حركة الحساب</h2><div class="scroll"><table><thead><tr><th>التاريخ</th><th>المرجع / الفاتورة</th><th>البيان</th><th>المستحق</th><th>السداد</th><th>الرصيد</th></tr></thead><tbody>${(report.rows || []).map(r=>`<tr><td>${e(r.date)}</td><td>${e(r.ref)}${r.invoice_no && r.invoice_no !== r.ref ? '<br>'+e(r.invoice_no) : ''}</td><td>${e(r.description)}${r.project ? '<br>'+e(r.project) : ''}</td><td class="num">${m(r.debit)}</td><td class="num">${m(r.credit)}</td><td class="num">${m(r.running_balance)}</td></tr>`).join('') || '<tr><td colspan="6">لا توجد حركة خلال الفترة.</td></tr>'}</tbody></table></div>
  <h2>الفواتير المفتوحة</h2><div class="scroll"><table><thead><tr><th>الفاتورة</th><th>تاريخها</th><th>الاستحقاق</th><th>الإجمالي</th><th>المدفوع</th><th>المتبقي</th></tr></thead><tbody>${(report.openInvoices || []).map(r=>`<tr><td>${e(r.invoice_no)}</td><td>${e(r.invoice_date)}</td><td>${e(r.due_date)}</td><td class="num">${m(r.invoice_total)}</td><td class="num">${m(r.paid_amount)}</td><td class="num">${m(r.balance)}</td></tr>`).join('') || '<tr><td colspan="6">لا توجد فواتير مفتوحة في هذا الكشف.</td></tr>'}</tbody></table></div>
  <footer><p>نسخة كشف حساب من المكتب المحاسبي بتاريخ إعدادها. لا يحل هذا الكشف محل الفاتورة الضريبية الأصلية.</p><p class="fine">${[c.company_name,c.unified_no ? 'الرقم الموحد: '+c.unified_no : '',c.vat_no ? 'الرقم الضريبي: '+c.vat_no : '',c.city,c.phone,c.email,c.website].filter(Boolean).map(e).join(' · ')}</p></footer></body></html>`;
}
